<<<<<<< HEAD
name: first_program
=======
name: dart_application_1
>>>>>>> b4e1707 (Intial commit)
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
